Compare the identified holes found with the older version of VoidFinder (from Jan. 2022) and the latest version of VoidFinder (from ~June 2022).

The files being compared are generated in the `_voidfinder_cython.pyx` files.

In [1]:
import numpy as np

from astropy.table import Table, hstack

# Output files

Read and parse the output files to convert into `astropy` tables (for easier comparisons).

In [2]:
def parse_debug_file(filename):
    '''
    Open and parse the output file, converting its contents into an astropy table.
    
    
    PARAMETERS
    ==========
    
    filename : string
        path to the output file
        
    
    RETURNS
    =======
    
    output_table : astropy table
        Table containing the contents of the given file.  Columns include:
          - "cell" : contains the cell coordinates from which the hole was grown
          - "hole" : contains the center hole coordinates
          - "R_hole" : radius of the hole
          - "gal1" : coodinates of the first bounding galaxy
          - "gal2" : coordinates of the second bounding galaxy
          - "gal3" : coordinates of the third bounding galaxy
          - "gal4" : coordinates of the fourth bounding galaxy
    '''
    
    # Read in file contents
    DEBUG_OUTPUT_FILE = open(filename, 'r')
    DEBUG_OUTPUT = DEBUG_OUTPUT_FILE.read()
    DEBUG_OUTPUT_FILE.close()
    
    # Split up the file contents by new line marker
    DEBUG_OUTPUT_lines = DEBUG_OUTPUT.split('\n')
    
    # Number of cells
    n_cells = int(len(DEBUG_OUTPUT_lines)/7)
    
    output_table = Table()
    output_table['cell'] = np.zeros((n_cells, 3), dtype=int)
    output_table['hole'] = np.zeros((n_cells, 3), dtype=np.float32)
    output_table['R_hole'] = np.zeros(n_cells, dtype=np.float32)
    output_table['gal1'] = np.zeros((n_cells, 3), dtype=np.float32)
    output_table['gal2'] = np.zeros((n_cells, 3), dtype=np.float32)
    output_table['gal3'] = np.zeros((n_cells, 3), dtype=np.float32)
    output_table['gal4'] = np.zeros((n_cells, 3), dtype=np.float32)
    
    for i in range(n_cells):
        
        output_table['cell'][i] = np.fromstring(DEBUG_OUTPUT_lines[7*i][19:-1], dtype=int, sep=', ')
        output_table['hole'][i] = np.fromstring(DEBUG_OUTPUT_lines[7*i+1][14:-1], sep=', ')
        output_table['R_hole'][i] = float(DEBUG_OUTPUT_lines[7*i+2][13:])
        output_table['gal1'][i] = np.fromstring(DEBUG_OUTPUT_lines[7*i+3][12:-1], sep=', ')
        output_table['gal2'][i] = np.fromstring(DEBUG_OUTPUT_lines[7*i+4][12:-1], sep=', ')
        output_table['gal3'][i] = np.fromstring(DEBUG_OUTPUT_lines[7*i+5][12:-1], sep=', ')
        output_table['gal4'][i] = np.fromstring(DEBUG_OUTPUT_lines[7*i+6][12:-1], sep=', ')
        
    return output_table

In [3]:
Jan_output = parse_debug_file('/Users/kellydouglass/Desktop/Voids_old/VAST/VoidFinder/vast/voidfinder/tests/VF_DEBUG_old.txt')

In [4]:
June_output = parse_debug_file('/Users/kellydouglass/Documents/Research/Voids/code/scripts/VF_DEBUG.txt')

In [26]:
linux_output = parse_debug_file('/Users/kellydouglass/Documents/Research/Voids/code/scripts/VF_DEBUG_linux.txt')

# Compare outputs

### Which cells result in a hole in the older version of VF but not the newer one?

In [5]:
keep_rows = []

for i, cell in enumerate(Jan_output['cell']):
    
    if not np.any(np.all(cell == June_output['cell'], axis=1)):
        
        keep_rows.append(i)
        
cells_in_old_not_new = Jan_output[keep_rows]

In [6]:
cells_in_old_not_new

<Table length=42>
  cell             hole             R_hole   ...           gal3                    gal4         
int64[3]        float32[3]         float32   ...        float32[3]              float32[3]      
-------- ------------------------ ---------- ... ----------------------- -----------------------
 25 .. 5  25.503057 .. 0.12753952   0.770878 ... 24.786995 .. 0.24853383         24.90938 .. 0.0
 25 .. 4  25.491405 .. -0.8926407 0.77086836 ...  26.083626 .. -0.784764  26.204426 .. -1.046259
 25 .. 3  25.448694 .. -1.9117334  0.7708331 ...   26.0439 .. -1.8301864 26.171494 .. -1.8301864
 27 .. 7   26.708588 .. 1.9780577 0.32367545 ...    26.5271 .. 2.0912433  26.542276 .. 1.8301864
 27 .. 4   26.46144 .. -0.9135296  0.1958153 ...  26.575676 .. -1.046259  26.582764 .. -0.784764
 27 .. 3   26.78695 .. -1.9575716 0.19079724 ... 26.779373 .. -1.8301864 26.764061 .. -2.0912433
 27 .. 4  26.930052 .. -0.9173873 0.19506155 ...  26.813072 .. -1.046259  26.820223 .. -0.784764
 27 .. 7     26.805674 .. 1.95894 0.18669249 ...  26.779373 .. 1.8301864  26.764061 .. 2.0912433
 27 .. 8   26.619202 .. 2.9885926  0.2368734 ...   26.705898 .. 2.873379  26.682442 .. 3.1336796
 28 .. 0   27.066986 .. -4.698505 0.77060556 ...   27.824398 .. -4.68978 26.310795 .. -4.7005954
 29 .. 0    29.10686 .. -4.890793  0.4841355 ...    28.73056 .. -4.68978   28.666954 .. -4.68978
 29 .. 8   28.757761 .. 2.9876542 0.24285607 ...  28.865294 .. 3.1336796  28.929338 .. 3.1336796
 30 .. 7   29.271624 .. 1.9496605 0.25004843 ...   29.40539 .. 2.0912433  29.422215 .. 1.8301864
 30 .. 4 29.532906 .. -0.91693693 0.19088693 ...  29.513632 .. -0.784764  29.467094 .. -0.784764
 25 .. 5  25.503057 .. 0.12753952   0.770878 ... 24.786995 .. 0.24853383         24.90938 .. 0.0
 25 .. 4  25.491405 .. -0.8926407 0.77086836 ...  26.083626 .. -0.784764  26.204426 .. -1.046259
 25 .. 3  25.448694 .. -1.9117334  0.7708331 ...   26.0439 .. -1.8301864 26.171494 .. -1.8301864
 27 .. 7   26.708588 .. 1.9780577 0.32367545 ...    26.5271 .. 2.0912433  26.542276 .. 1.8301864
 27 .. 4   26.46144 .. -0.9135296  0.1958153 ...  26.575676 .. -1.046259  26.582764 .. -0.784764
 27 .. 3   26.78695 .. -1.9575716 0.19079724 ... 26.779373 .. -1.8301864 26.764061 .. -2.0912433
 27 .. 4  26.930052 .. -0.9173873 0.19506155 ...  26.813072 .. -1.046259  26.820223 .. -0.784764
 27 .. 7     26.805674 .. 1.95894 0.18669249 ...  26.779373 .. 1.8301864  26.764061 .. 2.0912433
 27 .. 8   26.619202 .. 2.9885926  0.2368734 ...   26.705898 .. 2.873379  26.682442 .. 3.1336796
 28 .. 0   27.066986 .. -4.698505 0.77060556 ...   27.824398 .. -4.68978 26.310795 .. -4.7005954
 29 .. 0    29.10686 .. -4.890793  0.4841355 ...    28.73056 .. -4.68978   28.666954 .. -4.68978
 29 .. 8   28.757761 .. 2.9876542 0.24285607 ...  28.865294 .. 3.1336796  28.929338 .. 3.1336796
 30 .. 7   29.271624 .. 1.9496605 0.25004843 ...   29.40539 .. 2.0912433  29.422215 .. 1.8301864
 30 .. 4 29.532906 .. -0.91693693 0.19088693 ...  29.513632 .. -0.784764  29.467094 .. -0.784764
 25 .. 5  25.503057 .. 0.12753952   0.770878 ... 24.786995 .. 0.24853383         24.90938 .. 0.0
 25 .. 4  25.491405 .. -0.8926407 0.77086836 ...  26.083626 .. -0.784764  26.204426 .. -1.046259
 25 .. 3  25.448694 .. -1.9117334  0.7708331 ...   26.0439 .. -1.8301864 26.171494 .. -1.8301864
 27 .. 7   26.708588 .. 1.9780577 0.32367545 ...    26.5271 .. 2.0912433  26.542276 .. 1.8301864
 27 .. 4   26.46144 .. -0.9135296  0.1958153 ...  26.575676 .. -1.046259  26.582764 .. -0.784764
 27 .. 3   26.78695 .. -1.9575716 0.19079724 ... 26.779373 .. -1.8301864 26.764061 .. -2.0912433
 27 .. 4  26.930052 .. -0.9173873 0.19506155 ...  26.813072 .. -1.046259  26.820223 .. -0.784764
 27 .. 7     26.805674 .. 1.95894 0.18669249 ...  26.779373 .. 1.8301864  26.764061 .. 2.0912433
 27 .. 8   26.619202 .. 2.9885926  0.2368734 ...   26.705898 .. 2.873379  26.682442 .. 3.1336796
 28 .. 0   27.066986 .. -4.698505 0.77060556 ...   27.824398 .. -4.68978 26.310795 .. -4.7005954
 29 .

### Which cells result in a hole on my Macbook but not on Steve's linux box?

In [27]:
keep_rows = []

for i, cell in enumerate(June_output['cell']):
    
    if not np.any(np.all(cell == linux_output['cell'], axis=1)):
        
        keep_rows.append(i)
        
cells_in_mac_not_linux = June_output[keep_rows]

In [28]:
cells_in_mac_not_linux

<Table length=54>
  cell              hole             R_hole   ...           gal3                     gal4          
int64[3]         float32[3]         float32   ...        float32[3]               float32[3]       
-------- ------------------------- ---------- ... ------------------------ ------------------------
  8 .. 6     8.544049 .. 1.3138975  0.7518658 ...    7.863737 .. 1.2516894    9.227532 .. 1.3695748
  9 .. 3    9.532032 .. -1.7095493  1.1608478 ...   8.459867 .. -1.4843986    9.43995 .. -1.8220417
  9 .. 3   10.000571 .. -1.7769538  1.5003377 ...  11.407101 .. -2.0823333  11.424218 .. -1.9791981
 10 .. 3    10.09472 .. -1.5962033  1.5003415 ...  11.540481 .. -1.8759121   11.53227 .. -1.7724831
 10 .. 3   10.197747 .. -1.6527008   1.129539 ...   9.454116 .. -1.7317983  11.264354 .. -1.8759121
 14 .. 7    14.566133 .. 2.2584634 0.75568235 ...    13.886121 .. 2.215604   13.903702 .. 2.0861492
 14 .. 2   14.505856 .. -2.6654308  0.7556571 ...  15.209741 .. -2.8632083  13.847787 .. -2.4739976
 19 .. 3   19.409685 .. -1.6757195   0.759776 ...  18.660328 .. -1.6983587  20.110315 .. -1.6464987
 19 .. 8    19.654442 .. 3.2528112  0.7596786 ...   18.897408 .. 3.2161968    20.412184 .. 3.282846
 20 .. 1   20.401642 .. -3.6808329  0.7612165 ...  19.739687 .. -3.4635966  21.090668 .. -3.7109964
 20 .. 7    20.577602 .. 2.3662353 0.76131594 ...   21.266792 .. 2.3502598    21.30591 .. 2.5453064
 20 .. 7    20.551783 .. 2.3277795 0.76300204 ...   21.252266 .. 2.5069437   19.852089 .. 2.1550343
 22 .. 2    22.41204 .. -2.7308757  0.7629766 ...  21.676277 .. -2.5453064     21.6539 .. -2.740159
 22 .. 4       22.38 .. -0.6105032  0.8408344 ...     21.5511 .. -0.588573  23.158209 .. -0.6278112
 22 .. 4   22.474415 .. -0.3097859  1.1909385 ... 21.321676 .. -0.19621092  22.766987 .. -1.4641491
 22 .. 8    22.600742 .. 3.3352783 0.76472306 ...    21.86195 .. 3.3378386   21.968172 .. 3.1304567
 23 .. 8    23.644423 .. 3.3352783 0.76472306 ...    22.88618 .. 3.3378386   22.967957 .. 3.1304567
 24 .. 3   24.901634 .. -1.0330362  1.6153291 ...  23.929287 .. -2.2209306   25.77174 .. -2.3515735
 24 .. 3  24.977581 .. -0.11823312   2.397737 ...  23.795002 .. -1.9993198   25.77174 .. -2.3515735
 24 .. 1   24.428402 .. -3.7395544 0.76859343 ...  23.806536 .. -3.7550683   23.72794 .. -3.5217638
 25 .. 1    25.43199 .. -3.7395544 0.76859343 ...   24.68486 .. -3.7550683  24.773148 .. -3.7550683
 25 .. 3 25.071358 .. -0.038367055  2.4484088 ...  27.060537 .. -1.2422906 27.440247 .. -0.49704874
 25 .. 3   25.134861 .. -1.1456544  1.3766154 ...  26.058231 .. -1.8821189  24.401966 .. -2.2209306
     ...                       ...        ... ...                      ...                      ...
 10 .. 3    10.09472 .. -1.5962033  1.5003415 ...  11.540481 .. -1.8759121   11.53227 .. -1.7724831
 10 .. 3   10.197747 .. -1.6527008   1.129539 ...   9.454116 .. -1.7317983  11.264354 .. -1.8759121
 14 .. 7    14.566133 .. 2.2584634 0.75568235 ...    13.886121 .. 2.215604   13.903702 .. 2.0861492
 14 .. 2   14.505856 .. -2.6654308  0.7556571 ...  15.209741 .. -2.8632083  13.847787 .. -2.4739976
 19 .. 3   19.409685 .. -1.6757195   0.759776 ...  18.660328 .. -1.6983587  20.110315 .. -1.6464987
 19 .. 8    19.654442 .. 3.2528112  0.7596786 ...   18.897408 .. 3.2161968    20.412184 .. 3.282846
 20 .. 1   20.401642 .. -3.6808329  0.7612165 ...  19.739687 .. -3.4635966  21.090668 .. -3.7109964
 20 .. 7    20.577602 .. 2.3662353 0.76131594 ...   21.266792 .. 2.3502598    21.30591 .. 2.5453064
 20 .. 7    20.551783 .. 2.3277795 0.76300204 ...   21.252266 .. 2.5069437   19.852089 .. 2.1550343
 22 .. 2    22.41204 .. -2.7308757  0.7629766 ...  21.676277 .. -2.5453064     21.6539 .. -2.740159
 22 .. 4       22.38 .. -0.6105032  0.8408344 ...     21.5511 .. -0.588573  23.158209 .. -0.6278112
 22 .. 4   22.474415 .. -0.3097859  1.1909385 ... 21.321676 .. -0.19621092  22.766987 .. -1.4641491
 22 .. 8    22.600742 .. 3.3352783 0.76472306 ...    21.86195 .. 3.3378386   21.96

### And which cells result in a hole in the newer version of VF but not the older one?

In [7]:
keep_rows = []

for i, cell in enumerate(June_output['cell']):
    
    if not np.any(np.all(cell == Jan_output['cell'], axis=1)):
        
        keep_rows.append(i)
        
cells_in_new_not_old = June_output[keep_rows]

In [8]:
cells_in_new_not_old

<Table length=46>
  cell              hole             R_hole   ...           gal3                     gal4          
int64[3]         float32[3]         float32   ...        float32[3]               float32[3]       
-------- ------------------------- ---------- ... ------------------------ ------------------------
  8 .. 6     8.544049 .. 1.3138975  0.7518658 ...    7.863737 .. 1.2516894    9.227532 .. 1.3695748
  9 .. 3    9.532032 .. -1.7095493  1.1608478 ...   8.459867 .. -1.4843986    9.43995 .. -1.8220417
  9 .. 3   10.000571 .. -1.7769538  1.5003377 ...  11.407101 .. -2.0823333  11.424218 .. -1.9791981
 14 .. 7    14.566133 .. 2.2584634 0.75568235 ...    13.886121 .. 2.215604   13.903702 .. 2.0861492
 19 .. 3   19.409685 .. -1.6757195   0.759776 ...  18.660328 .. -1.6983587  20.110315 .. -1.6464987
 19 .. 8    19.654442 .. 3.2528112  0.7596786 ...   18.897408 .. 3.2161968    20.412184 .. 3.282846
 20 .. 1   20.401642 .. -3.6808329  0.7612165 ...  19.739687 .. -3.4635966  21.090668 .. -3.7109964
 20 .. 7    20.577602 .. 2.3662353 0.76131594 ...   21.266792 .. 2.3502598    21.30591 .. 2.5453064
 20 .. 7    20.551783 .. 2.3277795 0.76300204 ...   21.252266 .. 2.5069437   19.852089 .. 2.1550343
 22 .. 2    22.41204 .. -2.7308757  0.7629766 ...  21.676277 .. -2.5453064     21.6539 .. -2.740159
 22 .. 4       22.38 .. -0.6105032  0.8408344 ...     21.5511 .. -0.588573  23.158209 .. -0.6278112
 22 .. 4   22.474415 .. -0.3097859  1.1909385 ... 21.321676 .. -0.19621092  22.766987 .. -1.4641491
 22 .. 8    22.600742 .. 3.3352783 0.76472306 ...    21.86195 .. 3.3378386   21.968172 .. 3.1304567
 23 .. 8    23.644423 .. 3.3352783 0.76472306 ...    22.88618 .. 3.3378386   22.967957 .. 3.1304567
 24 .. 3   24.901634 .. -1.0330362  1.6153291 ...  23.929287 .. -2.2209306   25.77174 .. -2.3515735
 24 .. 3  24.977581 .. -0.11823312   2.397737 ...  23.795002 .. -1.9993198   25.77174 .. -2.3515735
 24 .. 1   24.428402 .. -3.7395544 0.76859343 ...  23.806536 .. -3.7550683   23.72794 .. -3.5217638
 25 .. 1    25.43199 .. -3.7395544 0.76859343 ...   24.68486 .. -3.7550683  24.773148 .. -3.7550683
 25 .. 3 25.071358 .. -0.038367055  2.4484088 ...  27.060537 .. -1.2422906 27.440247 .. -0.49704874
 25 .. 3   25.134861 .. -1.1456544  1.3766154 ...  26.058231 .. -1.8821189  24.401966 .. -2.2209306
 25 .. 1   25.369732 .. -3.7641056  0.7665848 ...  24.636173 .. -3.5464535  24.651686 .. -3.7665267
 26 .. 1   26.446333 .. -3.7395544 0.76859343 ...   25.77755 .. -3.5217638  25.683662 .. -3.7550683
 27 .. 4  27.673088 .. -0.37978137  1.0166018 ... 28.587317 .. -0.52320915   27.360287 .. -0.993946
  8 .. 6     8.544049 .. 1.3138975  0.7518658 ...    7.863737 .. 1.2516894    9.227532 .. 1.3695748
  9 .. 3    9.532032 .. -1.7095493  1.1608478 ...   8.459867 .. -1.4843986    9.43995 .. -1.8220417
  9 .. 3   10.000571 .. -1.7769538  1.5003377 ...  11.407101 .. -2.0823333  11.424218 .. -1.9791981
 14 .. 7    14.566133 .. 2.2584634 0.75568235 ...    13.886121 .. 2.215604   13.903702 .. 2.0861492
 19 .. 3   19.409685 .. -1.6757195   0.759776 ...  18.660328 .. -1.6983587  20.110315 .. -1.6464987
 19 .. 8    19.654442 .. 3.2528112  0.7596786 ...   18.897408 .. 3.2161968    20.412184 .. 3.282846
 20 .. 1   20.401642 .. -3.6808329  0.7612165 ...  19.739687 .. -3.4635966  21.090668 .. -3.7109964
 20 .. 7    20.577602 .. 2.3662353 0.76131594 ...   21.266792 .. 2.3502598    21.30591 .. 2.5453064
 20 .. 7    20.551783 .. 2.3277795 0.76300204 ...   21.252266 .. 2.5069437   19.852089 .. 2.1550343
 22 .. 2    22.41204 .. -2.7308757  0.7629766 ...  21.676277 .. -2.5453064     21.6539 .. -2.740159
 22 .. 4       22.38 .. -0.6105032  0.8408344 ...     21.5511 .. -0.588573  23.158209 .. -0.6278112
 22 .. 4   22.474415 .. -0.3097859  1.1909385 ... 21.321676 .. -0.19621092  22.766987 .. -1.4641491
 22 .. 8    22.600742 .. 3.3352783 0.76472306 ...    21.86195 .. 3.3378386   21.968172 .. 3.1304567
 23 .. 8    23.644423 .. 3.3352783 0.76472306 ...    22.88618 .. 3.3378386   22.96

In [29]:
keep_rows = []

for i, cell in enumerate(linux_output['cell']):
    
    if not np.any(np.all(cell == June_output['cell'], axis=1)):
        
        keep_rows.append(i)
        
cells_in_linux_not_mac = linux_output[keep_rows]

In [30]:
cells_in_linux_not_mac

<Table length=0>
  cell      hole     R_hole    gal1       gal2       gal3       gal4   
int64[3] float32[3] float32 float32[3] float32[3] float32[3] float32[3]
-------- ---------- ------- ---------- ---------- ---------- ----------

### For the cells that do result in holes in both versions, are they the same holes (bounded by the same four galaxies)?

##### Old v. new (all on Macbook)

In [9]:
keep_rows = []

for i in range(len(Jan_output)):
    
    matched_row = np.all(Jan_output['cell'][i] == June_output['cell'], axis=1)
    
    if np.any(matched_row):
        
        j = np.argwhere(matched_row)[0][0]
        
        gal1_comp = np.all(Jan_output['gal1'][i] == June_output['gal1'][j])
        gal2_comp = np.all(Jan_output['gal2'][i] == June_output['gal2'][j])
        gal3_comp = np.all(Jan_output['gal3'][i] == June_output['gal3'][j])
        gal4_comp = np.all(Jan_output['gal4'][i] == June_output['gal4'][j])
        
        if not np.all([gal1_comp, gal2_comp, gal3_comp, gal4_comp]):
            
            keep_rows.append([i, j])
            
keep_rows = np.array(keep_rows)
            
diff_gals = hstack([Jan_output[keep_rows[:,0]], June_output[keep_rows[:,1]]])

In [10]:
diff_gals

<Table length=528>
 cell_1            hole_1            R_hole_1  ...          gal3_2                   gal4_2         
int64[3]         float32[3]          float32   ...        float32[3]               float32[3]       
-------- -------------------------- ---------- ... ------------------------ ------------------------
  6 .. 5   6.5790586 .. 0.029432198  0.7506349 ...    5.8341603 .. 0.313798   5.848143 .. 0.26153487
  6 .. 4   6.5110364 .. -0.96791285 0.75062305 ...  7.255766 .. -0.84843546   7.277059 .. -0.7834199
  7 .. 5   7.4566526 .. 0.035972685  0.7512046 ...  6.7861304 .. 0.32691857  6.7605753 .. 0.26156476
  9 .. 4    9.582186 .. -0.92981595  1.1695617 ...  8.4517565 .. -0.7056423   8.477552 .. -0.7056423
  9 .. 5   9.498186 .. -0.042855795 0.83021754 ...   8.685982 .. 0.15696275   8.665341 .. 0.15696275
  9 .. 4      9.90121 .. -1.0309644  1.2979801 ...        10.3170185 .. 0.0   8.660525 .. -0.7056423
 10 .. 3    10.066066 .. -1.7769538  1.5003377 ...  11.540481 .. -1.8759121   11.53227 .. -1.7724831
 10 .. 4    10.527504 .. -0.9937879  1.1328816 ...  11.573928 .. -0.9408564  11.591199 .. -1.0451437
 10 .. 4   10.147962 .. -0.93773896  1.2661263 ...  11.344293 .. -0.8364973 11.383493 .. -0.73207456
 10 .. 3    10.175503 .. -1.8410616  1.1223885 ...   9.454116 .. -1.7317983  11.264354 .. -1.8759121
 11 .. 4    11.444602 .. -0.9442371  0.7535813 ... 12.153742 .. -0.82358384 12.108689 .. -0.70604557
 11 .. 5    11.476049 .. 0.05559415 0.75359255 ...  10.821865 .. 0.20928368   10.774357 .. 0.3139056
 12 .. 4    12.462216 .. -0.9442371  0.7535813 ...  13.22463 .. -0.70604557 11.729026 .. -0.73207456
 12 .. 5    12.496461 .. 0.05559415 0.75359255 ...   11.767325 .. 0.3139056  11.769567 .. 0.20928368
 12 .. 6     12.453661 .. 1.0550827  0.7535785 ...   11.696844 .. 1.1493516   13.170234 .. 1.4101559
 12 .. 3    12.544314 .. -1.9203117 0.75456715 ...  11.889422 .. -1.5271838  11.930651 .. -1.6440954
 12 .. 7     12.528939 .. 2.0433717   0.754561 ...   11.819018 .. 2.1104012   11.872259 .. 2.1104012
 13 .. 6     13.486898 .. 1.0553238 0.75459963 ...   12.734594 .. 1.2930205   14.201709 .. 1.3064297
 13 .. 5    13.523958 .. 0.06213464  0.7546136 ...    14.210121 .. 0.392382    14.251072 .. 0.392382
 13 .. 4   13.495131 .. -0.93135726 0.75460273 ...  12.781317 .. -0.5884535   12.81815 .. -0.5884535
 15 .. 4   15.501596 .. -0.97728187 0.75697887 ...  16.219818 .. -0.7846046   16.22538 .. -0.6277554
 15 .. 5    15.52642 .. 0.075215615  0.7569908 ...   16.232798 .. 0.3139255   16.16646 .. 0.15696873
 15 .. 6    15.501596 .. 0.97728187 0.75697887 ...   14.783719 .. 1.1501838    16.195723 .. 1.254746
     ...                        ...        ... ...                      ...                      ...
 26 .. 4    26.425144 .. -0.8926407 0.77086836 ...  25.803019 .. -0.7455258 25.807932 .. -0.49704874
 26 .. 5    26.437222 .. 0.12753952   0.770878 ...   25.81088 .. 0.24853383  27.166245 .. 0.52320915
 26 .. 6     26.417091 .. 1.1475643   0.770862 ...   25.787296 .. 1.2422906   27.133146 .. 1.5689901
 27 .. 2    27.457134 .. -2.9284968 0.77077234 ...  28.238026 .. -2.6128595    26.723059 .. -2.72971
 27 .. 3    27.536898 .. -1.9117334  0.7708331 ...  26.891691 .. -1.4905406   26.796581 .. -1.738677
 27 .. 4    27.62618 .. -0.89162374 0.81184465 ... 28.341574 .. -0.52320915   28.420242 .. -0.784764
 27 .. 5 27.479982 .. 2.5673907e-16  0.9677231 ...  28.428902 .. 0.26161456          28.34589 .. 0.0
 27 .. 6     27.574707 .. 1.1475643   0.770862 ...    28.23274 .. 1.3076743   28.307043 .. 1.5689901
 27 .. 7     27.536898 .. 1.9117334  0.7708331 ...    28.172523 .. 2.352141   28.238026 .. 2.6128595
 27 .. 8     27.457134 .. 2.9284968 0.77077234 ...   26.674082 .. 3.2240548   26.781078 .. 2.9769957
 27 .. 5  27.595852 .. 5.984086e-17  1.0912069 ...  28.590582 .. 0.26161456         28.591671 .. 0.0
 27 .. 0    27.512287 .. -4.9500856  0.7705756 ...    28.316286 .. -4.68978   28.199554 .. -4.947995
 28 .. 9      28.45499 .. 3.9416924  0.770

##### Mac v. linux (both new versions)

In [31]:
keep_rows = []

for i in range(len(linux_output)):
    
    matched_row = np.all(linux_output['cell'][i] == June_output['cell'], axis=1)
    
    if np.any(matched_row):
        
        j = np.argwhere(matched_row)[0][0]
        
        gal1_comp = np.all(linux_output['gal1'][i] == June_output['gal1'][j])
        gal2_comp = np.all(linux_output['gal2'][i] == June_output['gal2'][j])
        gal3_comp = np.all(linux_output['gal3'][i] == June_output['gal3'][j])
        gal4_comp = np.all(linux_output['gal4'][i] == June_output['gal4'][j])
        
        if not np.all([gal1_comp, gal2_comp, gal3_comp, gal4_comp]):
            
            keep_rows.append([i, j])
            
keep_rows = np.array(keep_rows)
            
diff_gals_linux = hstack([linux_output[keep_rows[:,0]], June_output[keep_rows[:,1]]])

In [32]:
diff_gals_linux

<Table length=171>
 cell_1            hole_1            R_hole_1  ...          gal3_2                   gal4_2         
int64[3]         float32[3]          float32   ...        float32[3]               float32[3]       
-------- -------------------------- ---------- ... ------------------------ ------------------------
  6 .. 5   6.5790586 .. 0.029432198  0.7506349 ...    5.8341603 .. 0.313798   5.848143 .. 0.26153487
  6 .. 4   6.5110364 .. -0.96791285 0.75062305 ...  7.255766 .. -0.84843546   7.277059 .. -0.7834199
  7 .. 5   7.4566526 .. 0.035972685  0.7512046 ...  6.7861304 .. 0.32691857  6.7605753 .. 0.26156476
  9 .. 4    9.582186 .. -0.92981595  1.1695617 ...  8.4517565 .. -0.7056423   8.477552 .. -0.7056423
  9 .. 5   9.481092 .. -0.042878814  0.8354817 ...   8.685982 .. 0.15696275   8.665341 .. 0.15696275
  9 .. 4      9.90121 .. -1.0309644  1.2979801 ...        10.3170185 .. 0.0   8.660525 .. -0.7056423
 10 .. 4   10.4679165 .. -0.9902354  1.1716266 ...  11.573928 .. -0.9408564  11.591199 .. -1.0451437
 10 .. 4   10.147962 .. -0.93773896  1.2661263 ...  11.344293 .. -0.8364973 11.383493 .. -0.73207456
 11 .. 4    11.444602 .. -0.9442371  0.7535813 ... 12.153742 .. -0.82358384 12.108689 .. -0.70604557
 11 .. 5    11.476049 .. 0.05559415 0.75359255 ...  10.821865 .. 0.20928368   10.774357 .. 0.3139056
 12 .. 4    12.462216 .. -0.9442371  0.7535813 ...  13.22463 .. -0.70604557 11.729026 .. -0.73207456
 12 .. 5    12.496461 .. 0.05559415 0.75359255 ...   11.767325 .. 0.3139056  11.769567 .. 0.20928368
 12 .. 6     12.453661 .. 1.0550827  0.7535785 ...   11.696844 .. 1.1493516   13.170234 .. 1.4101559
 12 .. 3    12.544314 .. -1.9203117 0.75456715 ...  11.889422 .. -1.5271838  11.930651 .. -1.6440954
 12 .. 7     12.528939 .. 2.0433717   0.754561 ...   11.819018 .. 2.1104012   11.872259 .. 2.1104012
 13 .. 6     13.486898 .. 1.0553238 0.75459963 ...   12.734594 .. 1.2930205   14.201709 .. 1.3064297
 13 .. 5    13.523958 .. 0.06213464  0.7546136 ...    14.210121 .. 0.392382    14.251072 .. 0.392382
 13 .. 4   13.495131 .. -0.93135726 0.75460273 ...  12.781317 .. -0.5884535   12.81815 .. -0.5884535
 15 .. 4   15.501596 .. -0.97728187 0.75697887 ...  16.219818 .. -0.7846046   16.22538 .. -0.6277554
 15 .. 5    15.52642 .. 0.075215615  0.7569908 ...   16.232798 .. 0.3139255   16.16646 .. 0.15696873
 15 .. 6    15.501596 .. 0.97728187 0.75697887 ...   14.783719 .. 1.1501838    16.195723 .. 1.254746
 16 .. 2    16.391136 .. -2.9192812  0.7568837 ...    15.69326 .. -2.579379  17.142931 .. -2.6587248
 16 .. 3    16.516079 .. -2.0261335 0.75693923 ...   17.29462 .. -1.7240274   17.27943 .. -1.8802078
     ...                        ...        ... ...                      ...                      ...
 26 .. 4    26.425144 .. -0.8926407 0.77086836 ...  25.803019 .. -0.7455258 25.807932 .. -0.49704874
 26 .. 5    26.437222 .. 0.12753952   0.770878 ...   25.81088 .. 0.24853383  27.166245 .. 0.52320915
 26 .. 6     26.417091 .. 1.1475643   0.770862 ...   25.787296 .. 1.2422906   27.133146 .. 1.5689901
 27 .. 2    27.457134 .. -2.9284968 0.77077234 ...  28.238026 .. -2.6128595    26.723059 .. -2.72971
 27 .. 3    27.536898 .. -1.9117334  0.7708331 ...  26.891691 .. -1.4905406   26.796581 .. -1.738677
 27 .. 4    27.62618 .. -0.89162374 0.81184465 ... 28.341574 .. -0.52320915   28.420242 .. -0.784764
 27 .. 5 27.479982 .. 2.5673907e-16  0.9677231 ...  28.428902 .. 0.26161456          28.34589 .. 0.0
 27 .. 6     27.62618 .. 0.89162374 0.81184465 ...    28.23274 .. 1.3076743   28.307043 .. 1.5689901
 27 .. 7     27.536898 .. 1.9117334  0.7708331 ...    28.172523 .. 2.352141   28.238026 .. 2.6128595
 27 .. 8     27.457134 .. 2.9284968 0.77077234 ...   26.674082 .. 3.2240548   26.781078 .. 2.9769957
 27 .. 5   27.36352 .. 5.984086e-17  1.2545054 ...  28.590582 .. 0.26161456         28.591671 .. 0.0
 27 .. 0    27.512287 .. -4.9500856  0.7705756 ...    28.316286 .. -4.68978   28.199554 .. -4.947995
 28 .. 9      28.45499 .. 3.9416924  0.770

##### Old version on Mac v. new version on linux

In [39]:
keep_rows = []

for i in range(len(linux_output)):
    
    matched_row = np.all(linux_output['cell'][i] == Jan_output['cell'], axis=1)
    
    if np.any(matched_row):
        
        j = np.argwhere(matched_row)[0][0]
        
        gal1_comp = np.all(linux_output['gal1'][i] == Jan_output['gal1'][j])
        gal2_comp = np.all(linux_output['gal2'][i] == Jan_output['gal2'][j])
        gal3_comp = np.all(linux_output['gal3'][i] == Jan_output['gal3'][j])
        gal4_comp = np.all(linux_output['gal4'][i] == Jan_output['gal4'][j])
        
        if not np.all([gal1_comp, gal2_comp, gal3_comp, gal4_comp]):
            
            keep_rows.append([i, j])
            
keep_rows = np.array(keep_rows)
            
diff_gals_oldMac_newLinux = hstack([linux_output[keep_rows[:,0]], Jan_output[keep_rows[:,1]]])

In [40]:
diff_gals_oldMac_newLinux

<Table length=20>
 cell_1            hole_1            R_hole_1  ...          gal3_2                   gal4_2         
int64[3]         float32[3]          float32   ...        float32[3]               float32[3]       
-------- -------------------------- ---------- ... ------------------------ ------------------------
  9 .. 5   9.481092 .. -0.042878814  0.8354817 ... 8.686975 .. -0.078484364          8.707288 .. 0.0
 10 .. 4   10.4679165 .. -0.9902354  1.1716266 ...  11.606667 .. -1.1493516  11.639872 .. -1.0451437
 22 .. 6    22.470993 .. 0.51628363  1.1909372 ...   21.31924 .. 0.39240688     22.43376 .. 1.255192
 23 .. 6    24.131496 .. 0.18318376   2.038927 ...   23.520187 .. 1.1115232   23.582727 .. 1.5556585
 23 .. 5   23.885582 .. 0.090109594  1.8399919 ...  22.306892 .. -0.6278112 23.455706 .. -0.22237237
 23 .. 7     23.582716 .. 1.8400773 0.85963666 ...    24.123552 .. 2.442372   22.786297 .. 2.0902874
 24 .. 5  24.63129 .. -6.466651e-17  2.0783286 ...         23.219433 .. 0.0         23.270952 .. 0.0
 24 .. 6    24.977581 .. 0.11823312   2.397737 ...   23.795002 .. 1.9993198  23.152035 .. 0.83700716
 24 .. 4   24.801394 .. -0.34045178  1.9989504 ...  24.912268 .. -0.9416331   24.903727 .. -1.176907
 25 .. 4    25.478863 .. -0.5888235  1.5345827 ...   26.830301 .. -0.993946   26.746368 .. -0.993946
 25 .. 5 25.123602 .. 2.0816682e-17  2.1066778 ...  26.273737 .. -0.9416331  27.440247 .. 0.49704874
 25 .. 4   25.078268 .. -0.34041277  1.9990306 ...  26.273737 .. -0.9416331    26.26473 .. -1.176907
 26 .. 7      26.490416 .. 1.806268  0.8714205 ...   27.310274 .. 1.9866811    27.29257 .. 2.2345338
 26 .. 6     25.448074 .. 0.3486722  2.0189438 ...  27.440247 .. 0.49704874    26.19983 .. 1.4120911
 26 .. 3     26.490416 .. -1.806268  0.8714205 ...  27.310274 .. -1.9866811   27.29257 .. -2.2345338
 26 .. 3    26.141233 .. -1.8032434  0.9878546 ...   25.614037 .. -2.586041  27.078356 .. -2.2345338
 26 .. 5  25.029373 .. 2.685352e-15  2.4942062 ... 26.758595 .. -0.49704874         28.511913 .. 0.0
 26 .. 6   25.071358 .. 0.038367055  2.4484088 ...    25.77174 .. 2.3515735   27.124863 .. 1.4905406
 27 .. 6     27.62618 .. 0.89162374 0.81184465 ...    28.328623 .. 1.046259   26.821104 .. 1.2422906
 27 .. 5   27.36352 .. 5.984086e-17  1.2545054 ...         28.591671 .. 0.0         28.669252 .. 0.0

#### Which version of VF is correct?

That is, which version is actually finding the right galaxies?

In [11]:
coord_min = np.array([0., 0., -5.46612512]) # Copied from terminal output

dl = 1.

In [41]:
hole_center_start = (diff_gals['cell_1'] + 0.5)*dl + coord_min
hole_center_start_linux = (diff_gals_linux['cell_1'] + 0.5)*dl + coord_min
hole_center_start_oldMac_newLinux = (diff_gals_oldMac_newLinux['cell_1'] + 0.5)*dl + coord_min

##### Distance between initial hole center and first galaxy found

In [13]:
Jan_gal1_dist2 = np.sum((hole_center_start - diff_gals['gal1_1'])**2, axis=1)
June_gal1_dist2 = np.sum((hole_center_start - diff_gals['gal1_2'])**2, axis=1)

In [36]:
mac_gal1_dist2 = np.sum((hole_center_start_linux - diff_gals_linux['gal1_2'])**2, axis=1)
linux_gal1_dist2 = np.sum((hole_center_start_linux - diff_gals_linux['gal1_1'])**2, axis=1)

In [42]:
oldMac_gal1_dist2 = np.sum((hole_center_start_oldMac_newLinux - diff_gals_oldMac_newLinux['gal1_2'])**2, axis=1)
newLinux_gal1_dist2 = np.sum((hole_center_start_oldMac_newLinux - diff_gals_oldMac_newLinux['gal1_1'])**2, axis=1)

In [44]:
#Jan_gal1_dist2 <= June_gal1_dist2
#linux_gal1_dist2 <= mac_gal1_dist2
oldMac_gal1_dist2 <= newLinux_gal1_dist2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

So January's version of VF always finds a closer galaxy.  And running the new code on Linux (Steve's machine) also finds a closer galaxy than when I run it on my Macbook.  :(

In [16]:
diff_gals['cell_1'][0]

array([6, 1, 5])

In [17]:
diff_gals['gal1_1'][0]

array([5.8419447 , 1.3487191 , 0.05232291], dtype=float32)

In [18]:
diff_gals['gal1_2'][0]

array([5.8366065 , 1.3474869 , 0.26153487], dtype=float32)

In [19]:
diff_gals['hole_1'][0]

array([6.5790586, 1.488689 , 0.0294322], dtype=float32)

In [20]:
diff_gals['hole_2'][0]

array([6.5715446, 1.4869888, 0.3236309], dtype=float32)

In [21]:
diff_gals['R_hole_1'][0]

0.7506349

In [22]:
diff_gals['R_hole_2'][0]

0.7506336

In [23]:
hole_center_start[0]

array([6.5       , 1.5       , 0.03387488])